apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi-registry
  labels:
    app: nifi-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi-registry
  template:
    metadata:
      labels:
        app: nifi-registry
    spec:
      containers:
        - name: nifi-registry
          image: apache/nifi-registry:latest
          ports:
            - containerPort: 18080
          env:
            - name: NIFI_REGISTRY_WEB_HTTP_PORT
              value: "18080"
---
apiVersion: v1
kind: Service
metadata:
  name: nifi-registry
spec:
  selector:
    app: nifi-registry
  ports:
    - protocol: TCP
      port: 18080
      targetPort: 18080
