scrape_configs:
  - job_name: 'nifi'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        regex: nifi
        action: keep
    metrics_path: /nifi-api/metrics
    scheme: http

  - job_name: 'nifi-registry'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        regex: nifi-registry
        action: keep
    metrics_path: /metrics
    scheme: http
